"""Public persistence protocol used by the service stages."""

from __future__ import annotations

from typing import Protocol


class Store(Protocol):
    def prepare(self, command: dict[str, str]) -> dict[str, str]: ...

    def get_event_id(self, command_key: str, occurrence_id: str) -> str | None: ...

    def append(self, command: dict[str, str]) -> str: ...

    def register(self, command: dict[str, str], event_id: str) -> None: ...

    def load(self, event_id: str) -> dict[str, str]: ...

    def effect_exists(self, event_id: str) -> str | None: ...

    def settle(self, event: dict[str, str]) -> str: ...

    def advance(self, sequence: int) -> None: ...
